# -*- coding: utf-8 -*-

###########################################################################
## gui.py - 整合並修正後的 15 個畫面基礎介面 (佈局衝突已解決)
###########################################################################

import wx
import wx.xrc
import gettext
_ = gettext.gettext

# =======================================================================
# 1. 初始畫面 (MainFrameBase)
# =======================================================================
class MainFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = wx.EmptyString, pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap1 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.m_bitmap1, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.book_search_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.book_search_input, 0, wx.ALL, 5 )
        self.query_button = wx.Button( self, wx.ID_ANY, _(u"查詢"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.query_button, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.login_button = wx.Button( self, wx.ID_ANY, _(u"登入/出"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.login_button, 0, wx.ALL, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 )
        bSizer4 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_staticText3 = wx.StaticText( self, wx.ID_ANY, _(u"推薦書籍"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText3.Wrap( -1 )
        bSizer4.Add( self.m_staticText3, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer4, 1, wx.EXPAND, 5 )
        gSizer1 = wx.GridSizer( 2, 3, 0, 0 )
        self.m_bitmap4 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        gSizer1.Add( self.m_bitmap4, 0, wx.ALL, 5 )
        self.m_bitmap5 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        gSizer1.Add( self.m_bitmap5, 0, wx.ALL, 5 )
        self.m_bitmap41 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        gSizer1.Add( self.m_bitmap41, 0, wx.ALL, 5 )
        self.m_staticText1 = wx.StaticText( self, wx.ID_ANY, _(u"MyLabel"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText1.Wrap( -1 )
        gSizer1.Add( self.m_staticText1, 0, wx.ALL, 5 )
        self.m_staticText2 = wx.StaticText( self, wx.ID_ANY, _(u"MyLabel"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText2.Wrap( -1 )
        gSizer1.Add( self.m_staticText2, 0, wx.ALL, 5 )
        self.m_staticText4 = wx.StaticText( self, wx.ID_ANY, _(u"MyLabel"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText4.Wrap( -1 )
        gSizer1.Add( self.m_staticText4, 0, wx.ALL, 5 )
        bSizer1.Add( gSizer1, 1, wx.ALL|wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.borrow_record_button = wx.Button( self, wx.ID_ANY, _(u"查看借閱紀錄"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer5.Add( self.borrow_record_button, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.query_button.Bind( wx.EVT_BUTTON, self.OnQueryButtonClick )
        self.login_button.Bind( wx.EVT_BUTTON, self.OnLoginButtonClick )
        self.borrow_record_button.Bind( wx.EVT_BUTTON, self.OnViewBorrowRecord )
    def __del__( self ): pass
    def OnQueryButtonClick( self, event ): event.Skip()
    def OnLoginButtonClick( self, event ): event.Skip()
    def OnViewBorrowRecord( self, event ): event.Skip()

# =======================================================================
# 2. 查詢書籍畫面 (QueryBookFrameBase)
# =======================================================================
class QueryBookFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"書籍查詢結果"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap1 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.m_bitmap1, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_textCtrl2 = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.m_textCtrl2, 0, wx.ALL, 5 )
        self.m_button1 = wx.Button( self, wx.ID_ANY, _(u"重新查詢"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.m_button1, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.back_to_main_button = wx.Button( self, wx.ID_ANY, _(u"返回主畫面"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.back_to_main_button, 0, wx.ALL, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 )
        bSizer4 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_bitmap13 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer4.Add( self.m_bitmap13, 0, wx.ALL, 5 )
        self.m_staticText13 = wx.StaticText( self, wx.ID_ANY, _(u"書籍資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText13.Wrap( -1 )
        bSizer4.Add( self.m_staticText13, 0, wx.ALL, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer4, 1, wx.EXPAND, 5 )
        bSizer41 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer41.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_bitmap131 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer41.Add( self.m_bitmap131, 0, wx.ALL, 5 )
        self.m_staticText131 = wx.StaticText( self, wx.ID_ANY, _(u"書籍資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText131.Wrap( -1 )
        bSizer41.Add( self.m_staticText131, 0, wx.ALL, 5 )
        bSizer41.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer41, 1, wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.VERTICAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.m_button1.Bind( wx.EVT_BUTTON, self.OnReQuery )
        self.back_to_main_button.Bind( wx.EVT_BUTTON, self.OnBackToMain )
    def __del__( self ): pass
    def OnReQuery( self, event ): event.Skip()
    def OnBackToMain( self, event ): event.Skip()

# =======================================================================
# 3. 身分選擇畫面 (IdentityChoiceFrameBase)
# =======================================================================
class IdentityChoiceFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"身分選擇"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_MENU ) )
        gSizer2 = wx.GridSizer( 2, 2, 0, 0 )
        self.m_bpButton3 = wx.BitmapButton( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, wx.BU_AUTODRAW|0 )
        gSizer2.Add( self.m_bpButton3, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.m_bpButton4 = wx.BitmapButton( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, wx.BU_AUTODRAW|0 )
        gSizer2.Add( self.m_bpButton4, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.admin_login_button = wx.Button( self, wx.ID_ANY, _(u"管理員登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        gSizer2.Add( self.admin_login_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.reader_login_button = wx.Button( self, wx.ID_ANY, _(u"讀者登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        gSizer2.Add( self.reader_login_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.SetSizer( gSizer2 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.admin_login_button.Bind( wx.EVT_BUTTON, self.OnAdminLogin )
        self.reader_login_button.Bind( wx.EVT_BUTTON, self.OnReaderLogin )
    def __del__( self ): pass
    def OnAdminLogin( self, event ): event.Skip()
    def OnReaderLogin( self, event ): event.Skip()

# =======================================================================
# 4. 讀者登入畫面 (ReaderLoginFormBase)
# =======================================================================
class ReaderLoginFormBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"讀者登入"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText9 = wx.StaticText( self, wx.ID_ANY, _(u"讀者登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText9.Wrap( -1 )
        bSizer2.Add( self.m_staticText9, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 ) # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL
        bSizer4 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText5 = wx.StaticText( self, wx.ID_ANY, _(u"帳號 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText5.Wrap( -1 )
        bSizer4.Add( self.m_staticText5, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.account_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer4.Add( self.account_input, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer4, 1, wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText6 = wx.StaticText( self, wx.ID_ANY, _(u"密碼 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText6.Wrap( -1 )
        bSizer5.Add( self.m_staticText6, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.password_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer5.Add( self.password_input, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText8 = wx.StaticText( self, wx.ID_ANY, _(u"沒有註冊嗎?"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText8.Wrap( -1 )
        bSizer8.Add( self.m_staticText8, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.register_button = wx.Button( self, wx.ID_ANY, _(u"註冊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.register_button, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.login_submit_button = wx.Button( self, wx.ID_ANY, _(u"登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.login_submit_button, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_button5 = wx.Button( self, wx.ID_ANY, _(u"忘記密碼"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.m_button5, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer8, 1, wx.EXPAND, 5 )
        bSizer9 = wx.BoxSizer( wx.VERTICAL )
        bSizer9.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer9, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.register_button.Bind( wx.EVT_BUTTON, self.OnRegisterClick )
        self.login_submit_button.Bind( wx.EVT_BUTTON, self.OnLoginSubmit )
    def __del__( self ): pass
    def OnRegisterClick( self, event ): event.Skip()
    def OnLoginSubmit( self, event ): event.Skip()

# =======================================================================
# 5. 註冊畫面 (RegisterFormBase)
# =======================================================================
class RegisterFormBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"帳號註冊"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText1 = wx.StaticText( self, wx.ID_ANY, _(u"帳號註冊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText1.Wrap( -1 )
        bSizer2.Add( self.m_staticText1, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText2 = wx.StaticText( self, wx.ID_ANY, _(u"帳號名稱 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText2.Wrap( -1 )
        bSizer5.Add( self.m_staticText2, 0, wx.ALL, 5 )
        self.account_name_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer5.Add( self.account_name_input, 0, wx.ALL, 5 )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        bSizer6 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer6.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText3 = wx.StaticText( self, wx.ID_ANY, _(u"密碼 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText3.Wrap( -1 )
        bSizer6.Add( self.m_staticText3, 0, wx.ALL, 5 )
        self.password_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer6.Add( self.password_input, 0, wx.ALL, 5 )
        bSizer6.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer6, 1, wx.EXPAND, 5 )
        bSizer7 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText4 = wx.StaticText( self, wx.ID_ANY, _(u"E-Mail :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText4.Wrap( -1 )
        bSizer7.Add( self.m_staticText4, 0, wx.ALL, 5 )
        self.email_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer7.Add( self.email_input, 0, wx.ALL, 5 )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer7, 1, wx.EXPAND, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.register_submit_button = wx.Button( self, wx.ID_ANY, _(u"註冊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.register_submit_button, 0, wx.ALL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer8, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.register_submit_button.Bind( wx.EVT_BUTTON, self.OnRegisterSubmit )
    def __del__( self ): pass
    def OnRegisterSubmit( self, event ): event.Skip()

# =======================================================================
# 6. 借閱紀錄 (BorrowRecordFrameBase)
# =======================================================================
class BorrowRecordFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"借閱紀錄"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer6 = wx.BoxSizer( wx.VERTICAL )
        bSizer7 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText5 = wx.StaticText( self, wx.ID_ANY, _(u"借閱紀錄"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText5.Wrap( -1 )
        bSizer7.Add( self.m_staticText5, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer7, 1, wx.EXPAND, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap5 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.m_bitmap5, 0, wx.ALL, 5 )
        self.m_staticText6 = wx.StaticText( self, wx.ID_ANY, _(u"書籍資訊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText6.Wrap( -1 )
        bSizer8.Add( self.m_staticText6, 0, wx.ALL, 5 )
        bSizer6.Add( bSizer8, 1, wx.EXPAND, 5 )
        bSizer9 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap6 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer9.Add( self.m_bitmap6, 0, wx.ALL, 5 )
        self.m_staticText7 = wx.StaticText( self, wx.ID_ANY, _(u"書籍資訊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText7.Wrap( -1 )
        bSizer9.Add( self.m_staticText7, 0, wx.ALL, 5 )
        bSizer6.Add( bSizer9, 1, wx.EXPAND, 5 )
        bSizer10 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap7 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer10.Add( self.m_bitmap7, 0, wx.ALL, 5 )
        self.m_staticText8 = wx.StaticText( self, wx.ID_ANY, _(u"書籍資訊"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText8.Wrap( -1 )
        bSizer10.Add( self.m_staticText8, 0, wx.ALL, 5 )
        bSizer6.Add( bSizer10, 1, wx.EXPAND, 5 )
        bSizer11 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer11.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.back_button = wx.Button( self, wx.ID_ANY, _(u"回上一頁"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer11.Add( self.back_button, 0, wx.ALL, 5 )
        bSizer6.Add( bSizer11, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.back_button.Bind( wx.EVT_BUTTON, self.OnBackClick )
    def __del__( self ): pass
    def OnBackClick( self, event ): event.Skip()

# =======================================================================
# 7. 書籍資料 (BookDetailFrameBase)
# =======================================================================
class BookDetailFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"書籍資料"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer6 = wx.BoxSizer( wx.VERTICAL )
        self.m_bitmap6 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer6.Add( self.m_bitmap6, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        bSizer7 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText4 = wx.StaticText( self, wx.ID_ANY, _(u"書名"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText4.Wrap( -1 )
        bSizer7.Add( self.m_staticText4, 0, wx.ALL, 5 )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer7, 1, wx.EXPAND, 5 ) # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL
        bSizer71 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer71.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText41 = wx.StaticText( self, wx.ID_ANY, _(u"作者"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText41.Wrap( -1 )
        bSizer71.Add( self.m_staticText41, 0, wx.ALL, 5 )
        bSizer71.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer71, 1, wx.EXPAND, 5 )
        bSizer72 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer72.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText42 = wx.StaticText( self, wx.ID_ANY, _(u"書號"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText42.Wrap( -1 )
        bSizer72.Add( self.m_staticText42, 0, wx.ALL, 5 )
        bSizer72.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer72, 1, wx.EXPAND, 5 )
        bSizer73 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer73.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText43 = wx.StaticText( self, wx.ID_ANY, _(u"ISBN"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText43.Wrap( -1 )
        bSizer73.Add( self.m_staticText43, 0, wx.ALL, 5 )
        bSizer73.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer73, 1, wx.EXPAND, 5 )
        bSizer74 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer74.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText44 = wx.StaticText( self, wx.ID_ANY, _(u"狀態"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer74.Add( self.m_staticText44, 0, wx.ALL, 5 )
        bSizer74.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer74, 1, wx.EXPAND, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.borrow_button = wx.Button( self, wx.ID_ANY, _(u"借閱"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.borrow_button, 0, wx.ALL, 5 )
        self.reserve_button = wx.Button( self, wx.ID_ANY, _(u"預約"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.reserve_button, 0, wx.ALL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer8, 1, wx.EXPAND, 5 )
        bSizer14 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer14.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer14, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.borrow_button.Bind( wx.EVT_BUTTON, self.OnBorrowClick )
        self.reserve_button.Bind( wx.EVT_BUTTON, self.OnReserveClick )
    def __del__( self ): pass
    def OnBorrowClick( self, event ): event.Skip()
    def OnReserveClick( self, event ): event.Skip()

# =======================================================================
# 8. 借閱結果 (BorrowResultFrameBase) - 佈局已修正
# =======================================================================
class BorrowResultFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"借閱結果"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_MENU ) )
        bSizer9 = wx.BoxSizer( wx.VERTICAL )
        bSizer10 = wx.BoxSizer( wx.VERTICAL )
        bSizer10.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText7 = wx.StaticText( self, wx.ID_ANY, _(u"借閱成功/失敗!"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText7.Wrap( -1 )
        bSizer10.Add( self.m_staticText7, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        self.m_staticText10 = wx.StaticText( self, wx.ID_ANY, _(u"if借閱失敗則此處顯示原因"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText10.Wrap( -1 )
        bSizer10.Add( self.m_staticText10, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        bSizer10.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL，只保留 wx.EXPAND
        bSizer9.Add( bSizer10, 1, wx.EXPAND, 5 ) 
        self.SetSizer( bSizer9 )
        self.Layout()
        self.Centre( wx.BOTH )
    def __del__( self ): pass

# =======================================================================
# 9. 預約結果 (ReserveResultFrameBase) - 佈局已修正
# =======================================================================
class ReserveResultFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"預約結果"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_MENU ) )
        bSizer9 = wx.BoxSizer( wx.VERTICAL )
        bSizer10 = wx.BoxSizer( wx.VERTICAL )
        bSizer10.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText7 = wx.StaticText( self, wx.ID_ANY, _(u"預約成功/失敗!"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText7.Wrap( -1 )
        bSizer10.Add( self.m_staticText7, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        self.m_staticText2 = wx.StaticText( self, wx.ID_ANY, _(u"預約失敗原因"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText2.Wrap( -1 )
        bSizer10.Add( self.m_staticText2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        bSizer10.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL，只保留 wx.EXPAND
        bSizer9.Add( bSizer10, 1, wx.EXPAND, 5 ) 
        self.SetSizer( bSizer9 )
        self.Layout()
        self.Centre( wx.BOTH )
    def __del__( self ): pass

# =======================================================================
# 10. 管理員登入 (AdminLoginFormBase)
# =======================================================================
class AdminLoginFormBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"管理員登入"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText9 = wx.StaticText( self, wx.ID_ANY, _(u"管理員登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText9.Wrap( -1 )
        bSizer2.Add( self.m_staticText9, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 ) # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL
        bSizer4 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText5 = wx.StaticText( self, wx.ID_ANY, _(u"帳號 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText5.Wrap( -1 )
        bSizer4.Add( self.m_staticText5, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.account_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer4.Add( self.account_input, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer4, 1, wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText6 = wx.StaticText( self, wx.ID_ANY, _(u"密碼 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText6.Wrap( -1 )
        bSizer5.Add( self.m_staticText6, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        self.password_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer5.Add( self.password_input, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.login_submit_button = wx.Button( self, wx.ID_ANY, _(u"登入"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.login_submit_button, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer8, 1, wx.EXPAND, 5 )
        bSizer9 = wx.BoxSizer( wx.VERTICAL )
        bSizer9.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer9, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.login_submit_button.Bind( wx.EVT_BUTTON, self.OnAdminLoginSubmit )
    def __del__( self ): pass
    def OnAdminLoginSubmit( self, event ): event.Skip()

# =======================================================================
# 11. 管理員頁面 (AdminPanelFrameBase)
# =======================================================================
class AdminPanelFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"管理員主頁"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer1 = wx.BoxSizer( wx.VERTICAL )
        bSizer2 = wx.BoxSizer( wx.HORIZONTAL )
        self.m_bitmap1 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.m_bitmap1, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.book_search_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.book_search_input, 0, wx.ALL, 5 )
        self.query_button = wx.Button( self, wx.ID_ANY, _(u"查詢"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.query_button, 0, wx.ALL, 5 )
        bSizer2.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.logout_button = wx.Button( self, wx.ID_ANY, _(u"登出"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer2.Add( self.logout_button, 0, wx.ALL, 5 )
        bSizer1.Add( bSizer2, 1, wx.EXPAND, 5 )
        bSizer4 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.add_book_button = wx.Button( self, wx.ID_ANY, _(u"新增書籍"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer4.Add( self.add_book_button, 0, wx.ALL|wx.EXPAND, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.borrow_record_button = wx.Button( self, wx.ID_ANY, _(u"借閱紀錄"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer4.Add( self.borrow_record_button, 0, wx.ALL|wx.EXPAND, 5 )
        bSizer4.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer4, 1, wx.EXPAND, 5 )
        bSizer41 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer41.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.view_reader_button = wx.Button( self, wx.ID_ANY, _(u"查看讀者資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer41.Add( self.view_reader_button, 0, wx.ALL|wx.EXPAND, 5 )
        bSizer41.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.add_reader_button = wx.Button( self, wx.ID_ANY, _(u"新增讀者資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer41.Add( self.add_reader_button, 0, wx.ALL|wx.EXPAND, 5 )
        bSizer41.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer41, 1, wx.EXPAND, 5 )
        bSizer5 = wx.BoxSizer( wx.VERTICAL )
        bSizer5.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer1.Add( bSizer5, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer1 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.query_button.Bind( wx.EVT_BUTTON, self.OnQueryBook )
        self.view_reader_button.Bind( wx.EVT_BUTTON, self.OnViewReaders )
        self.logout_button.Bind( wx.EVT_BUTTON, self.OnLogout )
        self.add_book_button.Bind( wx.EVT_BUTTON, self.OnAddBook )
        self.borrow_record_button.Bind( wx.EVT_BUTTON, self.OnViewBorrowRecord )
        self.add_reader_button.Bind( wx.EVT_BUTTON, self.OnAddReader )
    def __del__( self ): pass
    def OnQueryBook( self, event ): event.Skip()
    def OnViewReaders( self, event ): event.Skip()
    def OnLogout( self, event ): event.Skip()
    def OnAddBook( self, event ): event.Skip()
    def OnViewBorrowRecord( self, event ): event.Skip()
    def OnAddReader( self, event ): event.Skip()

# =======================================================================
# 12. 管理員書籍資料 (AdminBookDetailBase)
# =======================================================================
class AdminBookDetailBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"書籍資料管理"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer6 = wx.BoxSizer( wx.VERTICAL )
        self.m_bitmap6 = wx.StaticBitmap( self, wx.ID_ANY, wx.NullBitmap, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer6.Add( self.m_bitmap6, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5 )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.edit_button = wx.Button( self, wx.ID_ANY, _(u"修改資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.edit_button, 0, wx.ALL, 5 )
        self.delete_button = wx.Button( self, wx.ID_ANY, _(u"下架"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.delete_button, 0, wx.ALL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer8, 1, wx.EXPAND, 5 )
        bSizer14 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer14.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer14, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.edit_button.Bind( wx.EVT_BUTTON, self.OnEditBook )
        self.delete_button.Bind( wx.EVT_BUTTON, self.OnDeleteBook )
    def __del__( self ): pass
    def OnEditBook( self, event ): event.Skip()
    def OnDeleteBook( self, event ): event.Skip()

# =======================================================================
# 13. 修改書籍資料 (EditBookFormBase)
# =======================================================================
class EditBookFormBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"修改書籍資料"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )
        bSizer6 = wx.BoxSizer( wx.VERTICAL )
        bSizer25 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.cancel_button = wx.Button( self, wx.ID_ANY, _(u"取消"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.cancel_button, 0, wx.ALL, 5 )
        self.complete_button = wx.Button( self, wx.ID_ANY, _(u"完成"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.complete_button, 0, wx.ALL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer8, 1, wx.EXPAND, 5 )
        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )
        self.cancel_button.Bind( wx.EVT_BUTTON, self.OnCancel )
        self.complete_button.Bind( wx.EVT_BUTTON, self.OnComplete )
    def __del__( self ): pass
    def OnCancel( self, event ): event.Skip()
    def OnComplete( self, event ): event.Skip()

# -*- coding: utf-8 -*-
# gui.py: 項目 14. 查看讀者資料 (ReaderListFrameBase) 
# **已新增 wx.ListCtrl 元件以顯示列表資料**

class ReaderListFrameBase ( wx.Frame ):
    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"讀者列表"), pos = wx.DefaultPosition, size = wx.Size( 600,400 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )

        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )

        bSizer6 = wx.BoxSizer( wx.VERTICAL )

        # --- 新增 ListCtrl 元件來顯示讀者資料列表 ---
        self.reader_list_ctrl = wx.ListCtrl( self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.LC_REPORT )
        
        # 設定列表欄位 (這是讓 ListCtrl 成為表格的關鍵)
        self.reader_list_ctrl.InsertColumn( 0, _(u"讀者編號"), width=80 )
        self.reader_list_ctrl.InsertColumn( 1, _(u"姓名"), width=100 )
        self.reader_list_ctrl.InsertColumn( 2, _(u"E-Mail"), width=150 )
        self.reader_list_ctrl.InsertColumn( 3, _(u"信用分"), width=80 )
        
        bSizer6.Add( self.reader_list_ctrl, 1, wx.ALL|wx.EXPAND, 5 )
        # -----------------------------------------------

        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )

        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        
        # 新增一個按鈕用於返回
        self.back_button = wx.Button( self, wx.ID_ANY, _(u"返回"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.back_button, 0, wx.ALL, 5 )

        self.edit_button = wx.Button( self, wx.ID_ANY, _(u"修改資料"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.edit_button, 0, wx.ALL, 5 )
        
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )

        bSizer6.Add( bSizer8, 0, wx.EXPAND, 5 ) # 將比例設為 0，確保 ListCtrl 佔據主要空間

        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )

        self.edit_button.Bind( wx.EVT_BUTTON, self.OnEditReader )
        self.back_button.Bind( wx.EVT_BUTTON, self.OnBackClick ) # 綁定返回事件

    def __del__( self ): pass
    def OnEditReader( self, event ): event.Skip()
    def OnBackClick( self, event ): event.Skip() # 新增虛擬返回事件

# gui.py: 項目 15. 修改讀者資料 (EditReaderFormBase)
class EditReaderFormBase ( wx.Frame ):

    def __init__( self, parent ):
        wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = _(u"修改讀者資料"), pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )

        self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
        self.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_3DLIGHT ) )

        bSizer6 = wx.BoxSizer( wx.VERTICAL )

        bSizer6.Add( ( 0, 0), 1, wx.EXPAND, 5 )

        bSizer7 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText4 = wx.StaticText( self, wx.ID_ANY, _(u"讀者名 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText4.Wrap( -1 )
        bSizer7.Add( self.m_staticText4, 0, wx.ALL, 5 )
        self.reader_name_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer7.Add( self.reader_name_input, 0, wx.ALL, 5 )
        bSizer7.Add( ( 0, 0), 1, wx.EXPAND, 5 )

        # 修正點：移除 |wx.ALIGN_CENTER_HORIZONTAL
        bSizer6.Add( bSizer7, 1, wx.EXPAND, 5 ) 

        bSizer72 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer72.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText42 = wx.StaticText( self, wx.ID_ANY, _(u"讀者編號 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText42.Wrap( -1 )
        bSizer72.Add( self.m_staticText42, 0, wx.ALL, 5 )
        self.reader_id_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer72.Add( self.reader_id_input, 0, wx.ALL, 5 )
        bSizer72.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer72, 1, wx.EXPAND, 5 )

        bSizer73 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer73.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText43 = wx.StaticText( self, wx.ID_ANY, _(u"E-Mail :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText43.Wrap( -1 )
        bSizer73.Add( self.m_staticText43, 0, wx.ALL, 5 )
        self.email_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer73.Add( self.email_input, 0, wx.ALL, 5 )
        bSizer73.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer73, 1, wx.EXPAND, 5 )

        bSizer74 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer74.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.m_staticText44 = wx.StaticText( self, wx.ID_ANY, _(u"信用分 :"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText44.Wrap( -1 )
        bSizer74.Add( self.m_staticText44, 0, wx.ALL, 5 )
        self.credit_score_input = wx.TextCtrl( self, wx.ID_ANY, wx.EmptyString, wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer74.Add( self.credit_score_input, 0, wx.ALL, 5 )
        bSizer74.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer74, 1, wx.EXPAND, 5 )

        bSizer8 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        self.cancel_button = wx.Button( self, wx.ID_ANY, _(u"取消"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.cancel_button, 0, wx.ALL, 5 )
        self.complete_button = wx.Button( self, wx.ID_ANY, _(u"完成"), wx.DefaultPosition, wx.DefaultSize, 0 )
        bSizer8.Add( self.complete_button, 0, wx.ALL, 5 )
        bSizer8.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer8, 1, wx.EXPAND, 5 )

        bSizer14 = wx.BoxSizer( wx.HORIZONTAL )
        bSizer14.Add( ( 0, 0), 1, wx.EXPAND, 5 )
        bSizer6.Add( bSizer14, 1, wx.EXPAND, 5 )

        self.SetSizer( bSizer6 )
        self.Layout()
        self.Centre( wx.BOTH )

        # 重新命名按鈕以匹配邏輯
        self.cancel_button.Bind( wx.EVT_BUTTON, self.OnCancel )
        self.complete_button.Bind( wx.EVT_BUTTON, self.OnComplete )

    def __del__( self ): pass
    def OnCancel( self, event ): event.Skip()
    def OnComplete( self, event ): event.Skip()